$background = rgb(1D1B22)
$foreground = rgb(ECEEEC)
$color0 = rgb(434149)
$color1 = rgb(171D1B)
$color2 = rgb(284F31)
$color3 = rgb(535A68)
$color4 = rgb(758377)
$color5 = rgb(978B95)
$color6 = rgb(C8CDC8)
$color7 = rgb(DBDEDB)
$color8 = rgb(999B99)
$wallpaper_dominant = rgb(D4F675)
$wallpaper_border1 = rgb(A6CE61)
$wallpaper_border2 = rgb(4D7350)
$wallpaper_border3 = rgb(8FAB5B)
