$background = rgb(2B2B2C)
$foreground = rgb(EFFAFA)
$color0 = rgb(505051)
$color1 = rgb(9B4951)
$color2 = rgb(41629F)
$color3 = rgb(57705A)
$color4 = rgb(A09398)
$color5 = rgb(D4C270)
$color6 = rgb(D0F1F1)
$color7 = rgb(DFF0F0)
$color8 = rgb(9CA8A8)
