max-gamma = 150

profile {
    time = 07:30
    identity = true
}

profile {
    time = 20:30
    temperature = 5200
    gamma = 0.90
}

profile {
    time = 23:00
    temperature = 4200
    gamma = 0.82
}
