# -----------------------------------------------------
# Environment Variables
# name: "Default"
# -----------------------------------------------------

# Default Settings in ml4w.conf

env = GTK_THEME,Glassy-Originals-Gtk-Purple-Dark
env = QT_QPA_PLATFORMTHEME,qt5ct
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
