{
  "custom-styles": {
    "CSV": {
      "Column 1": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 1 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 4": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 4 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 5": {
        "selected-text-color": "#cfcfc2",
        "text-color": "#cfcfc2"
      },
      "Column 5 Separator": {
        "selected-text-color": "#cfcfc2",
        "text-color": "#cfcfc2"
      },
      "Column 6": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 6 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 7": {
        "selected-text-color": "#f44f4f",
        "text-color": "#f44f4f"
      },
      "Column 7 Separator": {
        "selected-text-color": "#f44f4f",
        "text-color": "#f44f4f"
      },
      "Column 8": {
        "selected-text-color": "#75bfc4",
        "text-color": "#609ca0"
      },
      "Column 8 Separator": {
        "selected-text-color": "#75bfc4",
        "text-color": "#609ca0"
      },
      "Column 9": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 9 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      }
    },
    "CSV (pipe)": {
      "Column 1": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 1 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 4": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 4 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 5": {
        "selected-text-color": "#cfcfc2",
        "text-color": "#cfcfc2"
      },
      "Column 5 Separator": {
        "selected-text-color": "#cfcfc2",
        "text-color": "#cfcfc2"
      },
      "Column 6": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 6 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 7": {
        "selected-text-color": "#f44f4f",
        "text-color": "#f44f4f"
      },
      "Column 7 Separator": {
        "selected-text-color": "#f44f4f",
        "text-color": "#f44f4f"
      },
      "Column 8": {
        "selected-text-color": "#75bfc4",
        "text-color": "#609ca0"
      },
      "Column 8 Separator": {
        "selected-text-color": "#75bfc4",
        "text-color": "#609ca0"
      },
      "Column 9": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 9 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      }
    },
    "CSV (semicolon)": {
      "Column 1": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 1 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 4": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 4 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 5": {
        "selected-text-color": "#cfcfc2",
        "text-color": "#cfcfc2"
      },
      "Column 5 Separator": {
        "selected-text-color": "#cfcfc2",
        "text-color": "#cfcfc2"
      },
      "Column 6": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 6 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 7": {
        "selected-text-color": "#f44f4f",
        "text-color": "#f44f4f"
      },
      "Column 7 Separator": {
        "selected-text-color": "#f44f4f",
        "text-color": "#f44f4f"
      },
      "Column 8": {
        "selected-text-color": "#75bfc4",
        "text-color": "#609ca0"
      },
      "Column 8 Separator": {
        "selected-text-color": "#75bfc4",
        "text-color": "#609ca0"
      },
      "Column 9": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 9 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      }
    },
    "CSV (whitespace)": {
      "Column 1": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 1 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 4": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 4 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 5": {
        "selected-text-color": "#cfcfc2",
        "text-color": "#cfcfc2"
      },
      "Column 5 Separator": {
        "selected-text-color": "#cfcfc2",
        "text-color": "#cfcfc2"
      },
      "Column 6": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 6 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 7": {
        "selected-text-color": "#f44f4f",
        "text-color": "#f44f4f"
      },
      "Column 7 Separator": {
        "selected-text-color": "#f44f4f",
        "text-color": "#f44f4f"
      },
      "Column 8": {
        "selected-text-color": "#75bfc4",
        "text-color": "#609ca0"
      },
      "Column 8 Separator": {
        "selected-text-color": "#75bfc4",
        "text-color": "#609ca0"
      },
      "Column 9": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 9 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      }
    },
    "TSV": {
      "Column 1": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 1 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 4": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 4 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 5": {
        "selected-text-color": "#cfcfc2",
        "text-color": "#cfcfc2"
      },
      "Column 5 Separator": {
        "selected-text-color": "#cfcfc2",
        "text-color": "#cfcfc2"
      },
      "Column 6": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 6 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#3daee9"
      },
      "Column 7": {
        "selected-text-color": "#f44f4f",
        "text-color": "#f44f4f"
      },
      "Column 7 Separator": {
        "selected-text-color": "#f44f4f",
        "text-color": "#f44f4f"
      },
      "Column 8": {
        "selected-text-color": "#75bfc4",
        "text-color": "#609ca0"
      },
      "Column 8 Separator": {
        "selected-text-color": "#75bfc4",
        "text-color": "#609ca0"
      },
      "Column 9": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      },
      "Column 9 Separator": {
        "selected-text-color": "#3daee9",
        "text-color": "#2980b9"
      }
    }
  },
  "editor-colors": {
    "BackgroundColor": "#64474748",
    "BracketMatching": "#3daee9",
    "CodeFolding": "#224e65",
    "CurrentLine": "#1f364f",
    "CurrentLineNumber": "#a5a6a8",
    "IconBorder": "#64474748",
    "IndentationLine": "#3a3f44",
    "LineNumbers": "#ffffff",
    "MarkBookmark": "#0404bf",
    "MarkBreakpointActive": "#8b0607",
    "MarkBreakpointDisabled": "#3a5f7a",
    "MarkBreakpointReached": "#6d6e07",
    "MarkError": "#da4453",
    "MarkExecution": "#4d4e50",
    "MarkWarning": "#f67400",
    "ModifiedLines": "#c04900",
    "ReplaceHighlight": "#808021",
    "SavedLines": "#1c8042",
    "SearchHighlight": "#414857",
    "Separator": "#643f4347",
    "SpellChecking": "#c0392b",
    "TabMarker": "#4d4d4d",
    "TemplateBackground": "#64474748",
    "TemplateFocusedPlaceholder": "#123723",
    "TemplatePlaceholder": "#123723",
    "TemplateReadOnlyPlaceholder": "#20364f",
    "TextSelection": "#1f364f",
    "WordWrapMarker": "#3a3f44"
  },
  "metadata": {
    "name": "Glass Dark",
    "revision": 1
  },
  "text-styles": {
    "Alert": {
      "background-color": "#14222d",
      "bold": true,
      "selected-text-color": "#95da4c",
      "text-color": "#95da4c"
    },
    "Annotation": {
      "selected-text-color": "#54aa75",
      "text-color": "#3f8058"
    },
    "Attribute": {
      "selected-text-color": "#fdbc4b",
      "text-color": "#2980b9"
    },
    "BaseN": {
      "selected-text-color": "#f67400",
      "text-color": "#f67400"
    },
    "BuiltIn": {
      "selected-text-color": "#75bfc4",
      "text-color": "#609ca0"
    },
    "Char": {
      "selected-text-color": "#3daee9",
      "text-color": "#3daee9"
    },
    "Comment": {
      "selected-text-color": "#808080",
      "text-color": "#7a7c7d"
    },
    "CommentVar": {
      "selected-text-color": "#94a3a4",
      "text-color": "#7f8c8d"
    },
    "Constant": {
      "bold": true,
      "selected-text-color": "#27aeae",
      "text-color": "#27aeae"
    },
    "ControlFlow": {
      "bold": true,
      "selected-text-color": "#fdbc4b",
      "text-color": "#fdbc4b"
    },
    "DataType": {
      "selected-text-color": "#fdbc4b",
      "text-color": "#2980b9"
    },
    "DecVal": {
      "selected-text-color": "#f67400",
      "text-color": "#f67400"
    },
    "Documentation": {
      "selected-text-color": "#3daee9",
      "text-color": "#2b6ea6"
    },
    "Error": {
      "selected-text-color": "#da4453",
      "text-color": "#da4453",
      "underline": true
    },
    "Extension": {
      "bold": true,
      "selected-text-color": "#bdc3c7",
      "text-color": "#3daee9"
    },
    "Float": {
      "selected-text-color": "#f67400",
      "text-color": "#f67400"
    },
    "Function": {
      "selected-text-color": "#3daee9",
      "text-color": "#2980b9"
    },
    "Import": {
      "selected-text-color": "#7cf5c1",
      "text-color": "#4ca97f"
    },
    "Information": {
      "selected-text-color": "#e46700",
      "text-color": "#c45b00"
    },
    "Keyword": {
      "bold": true,
      "selected-text-color": "#cfcfc2",
      "text-color": "#cfcfc2"
    },
    "Normal": {
      "selected-text-color": "#cfcfc2",
      "text-color": "#ffffff"
    },
    "Operator": {
      "selected-text-color": "#54aa75",
      "text-color": "#3f8058"
    },
    "Others": {
      "selected-text-color": "#27ae60",
      "text-color": "#27ae60"
    },
    "Preprocessor": {
      "selected-text-color": "#27ae60",
      "text-color": "#27ae60"
    },
    "RegionMarker": {
      "background-color": "#153042",
      "selected-text-color": "#3daee9",
      "text-color": "#2980b9"
    },
    "SpecialChar": {
      "selected-text-color": "#3daee9",
      "text-color": "#3daee9"
    },
    "SpecialString": {
      "selected-text-color": "#da4453",
      "text-color": "#da4453"
    },
    "String": {
      "selected-text-color": "#7cf5c1",
      "text-color": "#4ca97f"
    },
    "Variable": {
      "selected-text-color": "#3daee9",
      "text-color": "#2980b9"
    },
    "VerbatimString": {
      "selected-text-color": "#da4453",
      "text-color": "#da4453"
    },
    "Warning": {
      "selected-text-color": "#da4453",
      "text-color": "#da4453"
    }
  }
}
